<?php
// ============================================
// API Entry Point - نقطة الدخول الرئيسية
// ============================================

require_once __DIR__ . '/config/headers.php';

// API Documentation
$apiInfo = [
    'name' => 'YolaDent API',
    'version' => '1.0.0',
    'description' => 'REST API for YolaDent Dental Supplies Management',
    'base_url' => '/yola_dent_APIs/v1',
    'endpoints' => [
        'products' => [
            'GET /apis/products/' => 'Get all products',
            'GET /apis/products/?id={id}' => 'Get single product',
            'GET /apis/products/?action=categories' => 'Get all categories',
            'GET /apis/products/?action=suppliers' => 'Get all suppliers',
            'GET /apis/products/?action=low-stock' => 'Get low stock products',
            'GET /apis/products/?action=stats' => 'Get product statistics',
            'POST /apis/products/' => 'Create new product',
            'POST /apis/products/?action=add-stock' => 'Add stock to product',
            'POST /apis/products/?action=remove-stock' => 'Remove stock from product',
            'PUT /apis/products/?id={id}' => 'Update product',
            'DELETE /apis/products/?id={id}' => 'Delete product (soft delete)',
        ],
        'clients' => [
            'GET /apis/clients/' => 'Get all clients',
            'GET /apis/clients/?id={id}' => 'Get single client',
            'GET /apis/clients/?action=debtors' => 'Get clients with debt',
            'GET /apis/clients/?action=stats' => 'Get client statistics',
            'GET /apis/clients/?action=transactions&client_id={id}' => 'Get client transactions',
            'GET /apis/clients/?action=cities' => 'Get all cities',
            'POST /apis/clients/' => 'Create new client',
            'POST /apis/clients/?action=payment' => 'Record payment',
            'POST /apis/clients/?action=purchase' => 'Record purchase',
            'PUT /apis/clients/?id={id}' => 'Update client',
            'DELETE /apis/clients/?id={id}' => 'Delete client (soft delete)',
        ],
        'suppliers' => [
            'GET /apis/suppliers/' => 'Get all suppliers',
            'GET /apis/suppliers/?id={id}' => 'Get single supplier',
            'GET /apis/suppliers/?action=stats' => 'Get supplier statistics',
            'GET /apis/suppliers/?action=with-balance' => 'Get suppliers with balance',
            'GET /apis/suppliers/?action=products&supplier_id={id}' => 'Get supplier products',
            'POST /apis/suppliers/' => 'Create new supplier',
            'POST /apis/suppliers/?action=payment' => 'Record payment to supplier',
            'PUT /apis/suppliers/?id={id}' => 'Update supplier',
            'DELETE /apis/suppliers/?id={id}' => 'Delete supplier (soft delete)',
        ],
        'sales' => [
            'GET /apis/sales/' => 'Get all sales orders',
            'GET /apis/sales/?id={id}' => 'Get single order',
            'GET /apis/sales/?action=stats' => 'Get sales statistics',
            'GET /apis/sales/?action=daily-report&date={date}' => 'Get daily report',
            'GET /apis/sales/?action=top-products&limit={n}' => 'Get top selling products',
            'GET /apis/sales/?action=by-customer&customer_id={id}' => 'Get customer orders',
            'POST /apis/sales/' => 'Create new sales order',
            'POST /apis/sales/?action=complete' => 'Complete sale (update stock)',
            'POST /apis/sales/?action=payment' => 'Add payment to order',
            'POST /apis/sales/?action=cancel' => 'Cancel order',
            'PUT /apis/sales/?id={id}' => 'Update order',
            'DELETE /apis/sales/?id={id}' => 'Delete order (drafts only)',
        ],
        'supply' => [
            'GET /apis/supply/' => 'Get all supply orders',
            'GET /apis/supply/?id={id}' => 'Get single order',
            'GET /apis/supply/?action=stats' => 'Get supply statistics',
            'GET /apis/supply/?action=pending' => 'Get pending orders',
            'GET /apis/supply/?action=by-supplier&supplier_id={id}' => 'Get supplier orders',
            'POST /apis/supply/' => 'Create new supply order',
            'POST /apis/supply/?action=approve' => 'Approve order',
            'POST /apis/supply/?action=receive' => 'Receive full order (update stock)',
            'POST /apis/supply/?action=receive-item' => 'Receive single item',
            'POST /apis/supply/?action=cancel' => 'Cancel order',
            'PUT /apis/supply/?id={id}' => 'Update order',
            'DELETE /apis/supply/?id={id}' => 'Delete order (drafts only)',
        ],
        'warehouses' => [
            'GET /apis/warehouses/' => 'Get all warehouses',
            'GET /apis/warehouses/?id={id}' => 'Get single warehouse',
            'GET /apis/warehouses/?action=stats' => 'Get warehouse statistics',
            'GET /apis/warehouses/?action=default' => 'Get default warehouse',
            'GET /apis/warehouses/?action=stock&warehouse_id={id}' => 'Get warehouse stock',
            'POST /apis/warehouses/' => 'Create new warehouse',
            'POST /apis/warehouses/?action=set-default' => 'Set default warehouse',
            'PUT /apis/warehouses/?id={id}' => 'Update warehouse',
            'DELETE /apis/warehouses/?id={id}' => 'Delete warehouse (soft delete)',
        ],
        'transactions' => [
            'GET /apis/transactions/' => 'Get all transactions',
            'GET /apis/transactions/?id={id}' => 'Get single transaction',
            'GET /apis/transactions/?action=stats' => 'Get transaction statistics',
            'GET /apis/transactions/?action=by-product&product_id={id}' => 'Get transactions by product',
            'GET /apis/transactions/?action=by-type&type={type}' => 'Get transactions by type',
            'GET /apis/transactions/?action=by-date&start_date=&end_date=' => 'Get transactions by date',
            'GET /apis/transactions/?action=pending-approval' => 'Get pending approval transactions',
            'POST /apis/transactions/' => 'Create new transaction',
            'POST /apis/transactions/?action=approve' => 'Approve transaction',
            'PUT /apis/transactions/?id={id}' => 'Update transaction',
            'DELETE /apis/transactions/?id={id}' => 'Delete transaction',
        ],
        'reports' => [
            'GET /apis/reports/' => 'Get available reports list',
            'GET /apis/reports/?action=dashboard' => 'Dashboard statistics',
            'GET /apis/reports/?action=sales' => 'Sales report',
            'GET /apis/reports/?action=inventory' => 'Inventory report',
            'GET /apis/reports/?action=financial' => 'Financial report',
            'GET /apis/reports/?action=clients' => 'Clients report',
            'GET /apis/reports/?action=suppliers' => 'Suppliers report',
            'GET /apis/reports/?action=profit' => 'Profit report',
            'GET /apis/reports/?action=top-products' => 'Top products report',
            'GET /apis/reports/?action=low-stock' => 'Low stock alert report',
            'GET /apis/reports/?action=audit-log' => 'Audit log',
            'GET /apis/reports/?action=daily-summary' => 'Daily summary',
        ],
        'auth' => [
            'POST /apis/auth/?action=login' => 'Login user',
            'POST /apis/auth/?action=logout' => 'Logout user',
            'POST /apis/auth/?action=change-password' => 'Change password',
            'POST /apis/auth/?action=reset-password' => 'Reset password (admin)',
            'GET /apis/auth/' => 'Get all users',
            'GET /apis/auth/?id={id}' => 'Get single user',
            'POST /apis/auth/' => 'Create new user',
            'PUT /apis/auth/?id={id}' => 'Update user',
            'DELETE /apis/auth/?id={id}' => 'Delete user (soft delete)',
        ]
    ],
    'status' => 'running',
    'timestamp' => date('Y-m-d H:i:s')
];

sendSuccess($apiInfo, 'Welcome to YolaDent API');
